version: '3.8'
services:
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - cache:/data
    networks:
      ozon-parser:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ozon-parser"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      ozon-parser:
volumes:
  cache:
    driver: local
  pgdata:
    driver: local
networks:
  ozon-parser: