version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
    networks:
      ozon-parser:
    volumes:
      - ./data:/data
    environment:
      REDIS_HOST: "cache"
      REDIS_PASSWORD: ""
      DB_HOST: "db"
      DB_PASSWORD: "postgres"
      TZ: "Europe/Moscow"
    depends_on:
      - cache
      - db
  cache:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - cache:/data
    networks:
      ozon-parser:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ozon-parser"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      ozon-parser:
volumes:
  cache:
    driver: local
  pgdata:
    driver: local
networks:
  ozon-parser: