kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  labels:
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name:  "pv-{{ include "ozon-rank-parser.fullname" . }}"
  labels:
    type: local
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8s-volumes/ozon
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - "true"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "pvc-{{ include "ozon-rank-parser.fullname" . }}"
  labels:
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi