apiVersion: v1
kind: Pod
metadata:
  name: {{ include "ozon-rank-parser.fullname" . }}
  labels:
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
spec:
  restartPolicy: OnFailure
  containers:
    - name: {{ .Chart.Name }}
      image: "ghcr.io/execut/ozon-rank-parser:{{ .Values.image.tag | default .Chart.AppVersion }}"
      volumeMounts:
        - name: ozon-persistent-storage
          mountPath: /data
      env:
        - name: REDIS_HOST
          value: ozon-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "ozon"
              key: {{ template "redis.secretPasswordKey" }}
        - name: DB_HOST
          value: ozon-postgresql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "ozon"
              key: {{ template "postgresql.v1.adminPasswordKey" }}

  volumes:
    - name: ozon-persistent-storage
      persistentVolumeClaim:
        claimName: "pvc-{{ include "ozon-rank-parser.fullname" . }}"