apiVersion: v1
kind: Pod
metadata:
  name: {{ include "ozon-rank-parser.fullname" . }}
  labels:
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
spec:
  restartPolicy: Never
  containers:
    - name: {{ .Chart.Name }}
      image: "ghcr.io/execut/ozon-rank-parser:{{ .Values.image.tag | default .Chart.AppVersion }}"
      volumeMounts:
        - name: ozon-persistent-storage
          mountPath: /data
      env:
        - name: REDIS_HOST
          value: dev-redis-chart-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-redis-chart
              key: redis-password
        - name: DB_HOST
          value: dev-pg-postgresql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-pg-postgresql
              key: postgres-password

  volumes:
    - name: ozon-persistent-storage
      persistentVolumeClaim:
        claimName: "pvc-{{ include "ozon-rank-parser.fullname" . }}"