apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-redis-master-{{ include "ozon-rank-parser.fullname" . }}"
  labels:
    for-app: redis-{{ include "ozon-rank-parser.fullname" . }}
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8s-volumes/redis/master
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - "linux"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-redis-slave-{{ include "ozon-rank-parser.fullname" . }}"
  labels:
    for-app: redis-{{ include "ozon-rank-parser.fullname" . }}
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8s-volumes/redis/slave
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - "linux"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "pvc-redis-{{ include "ozon-rank-parser.fullname" . }}"
  labels:
    for-app: redis-{{ include "ozon-rank-parser.fullname" . }}
    {{- include "ozon-rank-parser.labels" . | nindent 4 }}
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi