apiVersion: v1
kind: Secret
metadata:
  name: ozon
data:
  {{- if .Release.IsInstall }}
  postgres-password: {{ randAlphaNum 20 | b64enc }}
  redis-password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  postgres-password:  {{ index (lookup "v1" "Secret" .Release.Namespace "ozon").data "postgres-password" }}
  redis-password:  {{ index (lookup "v1" "Secret" .Release.Namespace "ozon").data "redis-password" }}
  {{ end }}