kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-ozon
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8s-volumes/ozon
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - "true"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-for-ozon
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: ozon
spec:
  restartPolicy: Never
  containers:
    - image: ghcr.io/execut/ozon-rank-parser:1.0.7
      name: ozon
      volumeMounts:
        - name: ozon-persistent-storage
          mountPath: /data
      env:
        - name: REDIS_HOST
          value: dev-redis-chart-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-redis-chart
              key: redis-password
        - name: DB_HOST
          value: dev-pg-postgresql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-pg-postgresql
              key: postgres-password

  volumes:
    - name: ozon-persistent-storage
      persistentVolumeClaim:
        claimName: pvc-for-ozon