image:
  tag: ""

postgresql:
  primary:
    persistence:
      existingClaim: "pvc-pg-ozon-ozon-rank-parser"
  auth:
    existingSecret: "ozon"

redis:
  enabled: true
  auth:
    existingSecret: "ozon"
  master:
    persistence:
      existingClaim: "pvc-redis-ozon-ozon-rank-parser"
  replica:
    replicaCount: 1
    persistence:
      existingClaim: "pvc-redis-ozon-ozon-rank-parser"